### ISSUE TITLE
Creating and asking actors inside another actor never completes all the asks.

### ISSUE THREAD

**Issue by Harag** [mdbergmann/cl-gserver#20]
I am most probably abusing cl-gserver here but I was trying to test breaking up a long running task into many actors but all the sub actors dont complete their futures. Is it a bug or am I really messing up. (Just as a note I tried to create the sub actors as actors of the *system* or as actors of the main actor and the result is the same.)

There is a break in the code to show where things get stuck.

```
(defparameter *system* (asys:make-actor-system))

(defun blocking-task-spread-work ()
  ;;Message processing is blocked untill the main task is returned, 
  ;;The actual work is split between many actors and we wait for all of them
  ;;to finish
  
  (let ((blocking-actor
	  (ac:actor-of
	   *system*
	   (lambda ()
	     (act:make-actor 
	      (lambda (self msg state)
                                     
		(let ((output (get-universal-time)))
				       
		  (format t "~a : ~a : ~a~%" (act-cell:name self) msg output)
		  (if state
		      (cons output state)
		      (progn
		
			(let ((futures))
			  
			  (dotimes (i 5)
			    (push 
			     (act:ask
			      (ac:actor-of (act:context self) 
					   (lambda ()
					     (act:make-actor
					      (lambda (child-self msg state)
						(declare (ignore child-self))
						(let ((output msg))
						  (format t "~a : ~a~%" (act-cell:name self) output)
						  (sleep 1)
						  (cons output state)))
					      :name (format nil "child-~A" i))))
				      "Load Shard")
			     futures))

			  (loop do (break "~A" futures)
				until (every #'future:complete-p futures)))
			
			(cons output t)))))
	      :name "long-task")))))

    (future:on-completed
     (act:ask blocking-actor "Load shards" )
     (lambda (result)
	 (format t "Received final result: ~a~%" result)))
    
    (ac:stop *system* blocking-actor)))

(blocking-task-spread-work)
```

**Comment by mdbergmann** [comment]
Interesting. I will have a closer look in the evening.

**Comment by Harag** [comment]
FYI: If I use a router instead of a "parent actor" all futures are completed.

```

(defparameter *system* (asys:make-actor-system))

(defun router-spread-work-x ()
  ;;Blocked untill the main task is returned, 
  ;;The actual work is split between many actors and we wait for all of them
  ;;to finish
  
  (let ((router (router:make-router)))

    (let ((futures))

      (dotimes (i 5)
	(router:add-routee router (ac:actor-of *system* 
					(lambda ()
					  (act:make-actor
					   (lambda (child-self msg state)
                                             
					     (let ((output msg))
					       (format t "~a : ~a~%"
						       (act-cell:name child-self) output)
					       (sleep 1)
					       (cons output state)))
					   :name (format nil "routee-~A" i))))))
      
      (dotimes (i 5)
	(push (act:ask router "Load Shard") futures))

      (loop 
	    until (every #'future:complete-p futures))
      
      (format t "Received final result: ~A~%" futures))
    
    (router:stop router)))
```

**Comment by mdbergmann** [comment]
Yeah, I was actually thinking this as well. This is use-case for a router.
But I will have a look nonetheless.

**Comment by mdbergmann** [comment]
So, I know what's going on.

One important thing on actors is: don't block the message processing queue with long-running tasks.
What happens here is that all created actors use the `:shared` message dispatcher pool.
By default the actor-system spawns 4 (?) actors which act as message dispatchers.
Each message that is 'sent' is actually processed by those message dispatchers.

When actor A sends a message and the message is processed by dispatcher 1.
Now when actor B sends a message and the message is also processed by dispatcher 1, and 'receive' function of actor A does some long-running computation, then the message of actor B has to wait until the long running message was processed.
In the example above it is worse. :) Because actor A ('blocking-actor') waits on something from actor B, but message from B gets never processed, because message from actor A blocks. Dead-lock.

The strategy of choosing a message dispatcher to process the message is currently very dump. It is just chosen randomly.
This can for sure be improved by actually looking for dispatchers that are free, or round-robin, etc.
But this scenario can still happen no matter what.

So the pattern is, as I said, don't block the message processing.
This can be archieved by spawning a thread in 'receive' or use a third-party thread-pool library.
I first thought I'd integrate one, but I'd rather the user can choose.
The test [spawn-in-receive-test.lisp](https://github.com/mdbergmann/cl-gserver/blob/master/tests/spawn-in-receive-test.lisp) shows how this works.

An alternative is to give each actor its own message processing thread.
This can be done by creating the actors (`actor-of`) in the above example with `:dispatcher-type :pinned`.
`:pinned` pins a dedicated thread to the actor.
The example above will actually work when doing this.

**Comment by mdbergmann** [comment]
I would close this.
