### ISSUE TITLE
failed on ABCL

### ISSUE THREAD

**Issue by ijitai** [mdbergmann/cl-gserver#29]
cl-gserver can't be deployed on ABCL.

System info:
Macbook pro 2019, core i7, 16GB ram, big sur 11.3.1 
ABCL 1.8.0

It seems that "cl-murmurhash" has a problem.

-----------
`[package cl-murmurhash]
; in (DEFMACRO ~> ...)

; Caught STYLE-WARNING:
;   ; Note: deleting unused local function FLET ENLIST

...........................
...........
#<THREAD "interpreter" {4EFAFE9}>: Debugger invoked on condition of type STORAGE-CONDITION
  Stack overflow.
Restarts:
  0: RETRY                         Retry compiling #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-murmurhash" "cl-murmurhash">.
`

**Comment by mdbergmann** [comment]
Hmm. I wasn't aware I'm using 'cl-murmurhash'. Maybe pulled from somewhere.
At some point I checked on ABCL but didn't do recently.
Let me check.

**Comment by mdbergmann** [comment]
Looks like this dependency is pulled in by 'cl-hamt'. A pity, because FSet also doesn't work on ABCL.
Need to check. Maybe I have to fallback to CL hashtable.

**Comment by mdbergmann** [comment]
So I've replaced cl-hamt with an ordinary list.
But unfortunately ABCL also does not support 'atomics' package or CAS operations generally that was necessary for the latest router additions.
As sad as it is, but until this is fixed in ABCL cl-gserver will unfortunately not work on ABCL.
https://github.com/armedbear/abcl/issues/92

**Comment by mdbergmann** [comment]
For what it's worth, I've restructured the dependencies a bit.
It should now work on ABCL.

**Comment by mdbergmann** [comment]
except for #30
